export { CloudFormationWaitConditionHandle } from "@awboost/cfn-resource-types/AWS-CloudFormation-WaitConditionHandle";
export { CloudFrontDistribution } from "@awboost/cfn-resource-types/AWS-CloudFront-Distribution";
export { EC2InternetGateway } from "@awboost/cfn-resource-types/AWS-EC2-InternetGateway";
export { EC2SecurityGroup } from "@awboost/cfn-resource-types/AWS-EC2-SecurityGroup";
export { EC2VPC } from "@awboost/cfn-resource-types/AWS-EC2-VPC";
export { ECSService } from "@awboost/cfn-resource-types/AWS-ECS-Service";
export { ECSTaskDefinition } from "@awboost/cfn-resource-types/AWS-ECS-TaskDefinition";
export { ElastiCacheServerlessCache } from "@awboost/cfn-resource-types/AWS-ElastiCache-ServerlessCache";
export { ElasticLoadBalancingV2Listener } from "@awboost/cfn-resource-types/AWS-ElasticLoadBalancingV2-Listener";
export { ElasticLoadBalancingV2ListenerRule } from "@awboost/cfn-resource-types/AWS-ElasticLoadBalancingV2-ListenerRule";
export { ElasticLoadBalancingV2LoadBalancer } from "@awboost/cfn-resource-types/AWS-ElasticLoadBalancingV2-LoadBalancer";
export { ElasticLoadBalancingV2TargetGroup } from "@awboost/cfn-resource-types/AWS-ElasticLoadBalancingV2-TargetGroup";
export { EventsRule } from "@awboost/cfn-resource-types/AWS-Events-Rule";
export { IAMRole } from "@awboost/cfn-resource-types/AWS-IAM-Role";
export { LambdaEventSourceMapping } from "@awboost/cfn-resource-types/AWS-Lambda-EventSourceMapping";
export { type DeadLetterConfig } from "@awboost/cfn-resource-types/AWS-Lambda-Function";
export { RDSDBCluster } from "@awboost/cfn-resource-types/AWS-RDS-DBCluster";
export { RDSDBInstance } from "@awboost/cfn-resource-types/AWS-RDS-DBInstance";
export { RDSDBSecurityGroup } from "@awboost/cfn-resource-types/AWS-RDS-DBSecurityGroup";
export { RDSDBSubnetGroup } from "@awboost/cfn-resource-types/AWS-RDS-DBSubnetGroup";
export { S3Bucket } from "@awboost/cfn-resource-types/AWS-S3-Bucket";
export { SchedulerSchedule } from "@awboost/cfn-resource-types/AWS-Scheduler-Schedule";
export { SecretsManagerSecret } from "@awboost/cfn-resource-types/AWS-SecretsManager-Secret";
export { SQSQueue } from "@awboost/cfn-resource-types/AWS-SQS-Queue";
export { SSMParameter } from "@awboost/cfn-resource-types/AWS-SSM-Parameter";
export { Stack } from "@awboost/cfn-template-builder/stack";
export { Mapping } from "@awboost/cfn-template-builder/template/mapping";
export { Parameter, type ParameterInstance, } from "@awboost/cfn-template-builder/template/parameter";
export { type ResourceInstance } from "@awboost/cfn-template-builder/template/resource";
export interface BlueprintContext {
    projectName: string;
    environment: string;
    deploymentNumber: number;
    production: boolean;
}
