// @ts-nocheck
import * as __fd_glob_71 from "../content/docs/reference/api/test-helpers/interfaces/PerformedTask.md?collection=docs"
import * as __fd_glob_70 from "../content/docs/reference/api/introspection/functions/projectName.md?collection=docs"
import * as __fd_glob_69 from "../content/docs/reference/api/introspection/functions/projectFramework.md?collection=docs"
import * as __fd_glob_68 from "../content/docs/reference/api/introspection/functions/projectDependency.md?collection=docs"
import * as __fd_glob_67 from "../content/docs/reference/api/introspection/functions/projectDependencies.md?collection=docs"
import * as __fd_glob_66 from "../content/docs/reference/api/introspection/functions/packageVersion.md?collection=docs"
import * as __fd_glob_65 from "../content/docs/reference/api/introspection/interfaces/WorkloadInfo.md?collection=docs"
import * as __fd_glob_64 from "../content/docs/reference/api/introspection/interfaces/TaskInfo.md?collection=docs"
import * as __fd_glob_63 from "../content/docs/reference/api/introspection/interfaces/DatabaseWorkloadInfo.md?collection=docs"
import * as __fd_glob_62 from "../content/docs/reference/api/introspection/interfaces/CronInto.md?collection=docs"
import * as __fd_glob_61 from "../content/docs/reference/api/introspection/interfaces/BuildManifest.md?collection=docs"
import * as __fd_glob_60 from "../content/docs/reference/api/introspection/interfaces/BucketInfo.md?collection=docs"
import * as __fd_glob_59 from "../content/docs/reference/api/test-helpers/functions/truncatePostgresTables.md?collection=docs"
import * as __fd_glob_58 from "../content/docs/reference/api/test-helpers/functions/performedTasks.md?collection=docs"
import * as __fd_glob_57 from "../content/docs/reference/api/test-helpers/functions/flushRedis.md?collection=docs"
import * as __fd_glob_56 from "../content/docs/reference/api/test-helpers/functions/clearPerformedTasks.md?collection=docs"
import * as __fd_glob_55 from "../content/docs/reference/api/introspection/variables/manifestJsonSchema.md?collection=docs"
import * as __fd_glob_54 from "../content/docs/reference/api/main/interfaces/Workload.md?collection=docs"
import * as __fd_glob_53 from "../content/docs/reference/api/main/interfaces/TaskOptions.md?collection=docs"
import * as __fd_glob_52 from "../content/docs/reference/api/main/interfaces/StatelessWorkload.md?collection=docs"
import * as __fd_glob_51 from "../content/docs/reference/api/main/interfaces/StatefulWorkloadWithClient.md?collection=docs"
import * as __fd_glob_50 from "../content/docs/reference/api/main/interfaces/StatefulWorkload.md?collection=docs"
import * as __fd_glob_49 from "../content/docs/reference/api/main/interfaces/RetryOptions.md?collection=docs"
import * as __fd_glob_48 from "../content/docs/reference/api/main/interfaces/LifecycleWorkload.md?collection=docs"
import * as __fd_glob_47 from "../content/docs/reference/api/main/interfaces/Database.md?collection=docs"
import * as __fd_glob_46 from "../content/docs/reference/api/main/interfaces/CronOptions.md?collection=docs"
import * as __fd_glob_45 from "../content/docs/reference/api/main/interfaces/ContainerConfig.md?collection=docs"
import * as __fd_glob_44 from "../content/docs/reference/api/main/interfaces/Configuration.md?collection=docs"
import * as __fd_glob_43 from "../content/docs/reference/api/main/interfaces/BucketOptions.md?collection=docs"
import * as __fd_glob_42 from "../content/docs/reference/api/main/type-aliases/PublicAccess.md?collection=docs"
import * as __fd_glob_41 from "../content/docs/reference/api/main/type-aliases/AccessGrant.md?collection=docs"
import * as __fd_glob_40 from "../content/docs/reference/api/main/functions/bucketLocalConfiguration.md?collection=docs"
import * as __fd_glob_39 from "../content/docs/reference/api/main/functions/broadcastClient.md?collection=docs"
import * as __fd_glob_38 from "../content/docs/reference/api/main/functions/BroadcastProvider.md?collection=docs"
import * as __fd_glob_37 from "../content/docs/reference/api/main/classes/Task.md?collection=docs"
import * as __fd_glob_36 from "../content/docs/reference/api/main/classes/Redis.md?collection=docs"
import * as __fd_glob_35 from "../content/docs/reference/api/main/classes/PostgresDatabase.md?collection=docs"
import * as __fd_glob_34 from "../content/docs/reference/api/main/classes/Cron.md?collection=docs"
import * as __fd_glob_33 from "../content/docs/reference/api/main/classes/ChannelData.md?collection=docs"
import * as __fd_glob_32 from "../content/docs/reference/api/main/classes/Bucket.md?collection=docs"
import * as __fd_glob_31 from "../content/docs/reference/api/main/classes/BroadcastPublisher.md?collection=docs"
import * as __fd_glob_30 from "../content/docs/reference/api/main/classes/Broadcast.md?collection=docs"
import * as __fd_glob_29 from "../content/docs/reference/api/main/classes/Bootstrap.md?collection=docs"
import * as __fd_glob_28 from "../content/docs/reference/api/main/classes/BeforeRollout.md?collection=docs"
import * as __fd_glob_27 from "../content/docs/reference/api/main/classes/AfterRollout.md?collection=docs"
import * as __fd_glob_26 from "../content/docs/workloads/stateful/redis.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/workloads/stateful/postgres.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/workloads/stateful/bucket.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/workloads/stateless/task.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/workloads/stateless/cron.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/workloads/stateless/broadcast.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/workloads/app-lifecycle/bootstrap.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/workloads/app-lifecycle/before-rollout.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/workloads/app-lifecycle/after-rollout.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/reference/cli/trigger-cron.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/reference/cli/stop-test.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/reference/cli/stop-dev.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/reference/cli/status-test.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/reference/cli/status-dev.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/reference/cli/start-test.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/reference/cli/start-dev.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/reference/cli/pull.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/reference/cli/build.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/guide/why-workloads.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/guide/testing.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/guide/quick-start.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/guide/installation.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/guide/configuration.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/workloads/app-lifecycle/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/reference/cli/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../lib/source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "reference/cli/meta.json": __fd_glob_1, "workloads/app-lifecycle/meta.json": __fd_glob_2, }, {"index.mdx": __fd_glob_3, "guide/configuration.mdx": __fd_glob_4, "guide/installation.mdx": __fd_glob_5, "guide/quick-start.mdx": __fd_glob_6, "guide/testing.mdx": __fd_glob_7, "guide/why-workloads.mdx": __fd_glob_8, "reference/cli/build.mdx": __fd_glob_9, "reference/cli/pull.mdx": __fd_glob_10, "reference/cli/start-dev.mdx": __fd_glob_11, "reference/cli/start-test.mdx": __fd_glob_12, "reference/cli/status-dev.mdx": __fd_glob_13, "reference/cli/status-test.mdx": __fd_glob_14, "reference/cli/stop-dev.mdx": __fd_glob_15, "reference/cli/stop-test.mdx": __fd_glob_16, "reference/cli/trigger-cron.mdx": __fd_glob_17, "workloads/app-lifecycle/after-rollout.mdx": __fd_glob_18, "workloads/app-lifecycle/before-rollout.mdx": __fd_glob_19, "workloads/app-lifecycle/bootstrap.mdx": __fd_glob_20, "workloads/stateless/broadcast.mdx": __fd_glob_21, "workloads/stateless/cron.mdx": __fd_glob_22, "workloads/stateless/task.mdx": __fd_glob_23, "workloads/stateful/bucket.mdx": __fd_glob_24, "workloads/stateful/postgres.mdx": __fd_glob_25, "workloads/stateful/redis.mdx": __fd_glob_26, "reference/api/main/classes/AfterRollout.md": __fd_glob_27, "reference/api/main/classes/BeforeRollout.md": __fd_glob_28, "reference/api/main/classes/Bootstrap.md": __fd_glob_29, "reference/api/main/classes/Broadcast.md": __fd_glob_30, "reference/api/main/classes/BroadcastPublisher.md": __fd_glob_31, "reference/api/main/classes/Bucket.md": __fd_glob_32, "reference/api/main/classes/ChannelData.md": __fd_glob_33, "reference/api/main/classes/Cron.md": __fd_glob_34, "reference/api/main/classes/PostgresDatabase.md": __fd_glob_35, "reference/api/main/classes/Redis.md": __fd_glob_36, "reference/api/main/classes/Task.md": __fd_glob_37, "reference/api/main/functions/BroadcastProvider.md": __fd_glob_38, "reference/api/main/functions/broadcastClient.md": __fd_glob_39, "reference/api/main/functions/bucketLocalConfiguration.md": __fd_glob_40, "reference/api/main/type-aliases/AccessGrant.md": __fd_glob_41, "reference/api/main/type-aliases/PublicAccess.md": __fd_glob_42, "reference/api/main/interfaces/BucketOptions.md": __fd_glob_43, "reference/api/main/interfaces/Configuration.md": __fd_glob_44, "reference/api/main/interfaces/ContainerConfig.md": __fd_glob_45, "reference/api/main/interfaces/CronOptions.md": __fd_glob_46, "reference/api/main/interfaces/Database.md": __fd_glob_47, "reference/api/main/interfaces/LifecycleWorkload.md": __fd_glob_48, "reference/api/main/interfaces/RetryOptions.md": __fd_glob_49, "reference/api/main/interfaces/StatefulWorkload.md": __fd_glob_50, "reference/api/main/interfaces/StatefulWorkloadWithClient.md": __fd_glob_51, "reference/api/main/interfaces/StatelessWorkload.md": __fd_glob_52, "reference/api/main/interfaces/TaskOptions.md": __fd_glob_53, "reference/api/main/interfaces/Workload.md": __fd_glob_54, "reference/api/introspection/variables/manifestJsonSchema.md": __fd_glob_55, "reference/api/test-helpers/functions/clearPerformedTasks.md": __fd_glob_56, "reference/api/test-helpers/functions/flushRedis.md": __fd_glob_57, "reference/api/test-helpers/functions/performedTasks.md": __fd_glob_58, "reference/api/test-helpers/functions/truncatePostgresTables.md": __fd_glob_59, "reference/api/introspection/interfaces/BucketInfo.md": __fd_glob_60, "reference/api/introspection/interfaces/BuildManifest.md": __fd_glob_61, "reference/api/introspection/interfaces/CronInto.md": __fd_glob_62, "reference/api/introspection/interfaces/DatabaseWorkloadInfo.md": __fd_glob_63, "reference/api/introspection/interfaces/TaskInfo.md": __fd_glob_64, "reference/api/introspection/interfaces/WorkloadInfo.md": __fd_glob_65, "reference/api/introspection/functions/packageVersion.md": __fd_glob_66, "reference/api/introspection/functions/projectDependencies.md": __fd_glob_67, "reference/api/introspection/functions/projectDependency.md": __fd_glob_68, "reference/api/introspection/functions/projectFramework.md": __fd_glob_69, "reference/api/introspection/functions/projectName.md": __fd_glob_70, "reference/api/test-helpers/interfaces/PerformedTask.md": __fd_glob_71, });